/* Auto-generated by tools/sync_symbols.py — do not edit.
 * Source: symbols.toml (Legacy of Kain Soul Reaver)
 * Progressive symbols: discover → label → manipulate via PSX_FN_*.
 */
#pragma once

/* guessed: SYSTEM.CNF / EXE entry PC (probe seed) */
#define PSX_FN_BootEntry 0x800B72D0u
#define func_800B72D0 BootEntry  /* alias */
